### ISSUE TITLE
Метрополитен 1

### ISSUE THREAD

**Issue by WonderWaffle4** [WonderWaffle4/wasp_DZ#1]
@vdetstvepil

**Comment by vdetstvepil** [comment]
**Файл Station.cs**
- 33 строка. Если присвоишь один список другому, то элементы из второго списка не перепрыгнут в первый. Знаком равно ты просто присваиваешь первому списку ссылку на второй список. Если у тебя второй список поменяется, удалится и т.п., изменения в первом списке проявятся немедленно. Как избежать: просто через цикл foreach добавить элементы из второго списка в основной список. Или воспользоваться функцией AddRange.

**Comment by vdetstvepil** [comment]
Принято. Только поправь ошибки.

**Comment by WonderWaffle4** [comment]
@vdetstvepil Вроде исправил

**Comment by vdetstvepil** [comment]
супер! теперь правильно
